// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, key_hash, label, client_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, key_hash, label, client_id, expires_at, created_at
`

type CreateAPIKeyParams struct {
	UserID    int64              `json:"user_id"`
	KeyHash   string             `json:"key_hash"`
	Label     pgtype.Text        `json:"label"`
	ClientID  pgtype.Text        `json:"client_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.KeyHash,
		arg.Label,
		arg.ClientID,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.Label,
		&i.ClientID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM api_keys
WHERE id = $1 AND user_id = $2
`

type DeleteAPIKeyParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByAPIKeyHash = `-- name: GetUserByAPIKeyHash :one
SELECT u.id, u.username, u.password_hash, u.created_at FROM api_keys ak
JOIN users u ON u.id = ak.user_id
WHERE ak.key_hash = $1
  AND (ak.expires_at IS NULL OR ak.expires_at > now())
`

func (q *Queries) GetUserByAPIKeyHash(ctx context.Context, keyHash string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKeyHash, keyHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, key_hash, label, client_id, expires_at, created_at FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID int64) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KeyHash,
			&i.Label,
			&i.ClientID,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
