// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: languages.sql

package sqlc

import (
	"context"
)

const countLanguagesByUser = `-- name: CountLanguagesByUser :one
SELECT count(*) FROM languages
WHERE user_id = $1
`

func (q *Queries) CountLanguagesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLanguagesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLanguage = `-- name: CreateLanguage :one
INSERT INTO languages (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, created_at
`

type CreateLanguageParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error) {
	row := q.db.QueryRow(ctx, createLanguage, arg.UserID, arg.Name)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listLanguagesByUser = `-- name: ListLanguagesByUser :many
SELECT id, user_id, name, created_at FROM languages
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListLanguagesByUser(ctx context.Context, userID int64) ([]Language, error) {
	rows, err := q.db.Query(ctx, listLanguagesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
