// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type WordState string

const (
	WordStateNew       WordState = "new"
	WordStateLearning  WordState = "learning"
	WordStateConfident WordState = "confident"
	WordStateMastered  WordState = "mastered"
)

func (e *WordState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WordState(s)
	case string:
		*e = WordState(s)
	default:
		return fmt.Errorf("unsupported scan type for WordState: %T", src)
	}
	return nil
}

type NullWordState struct {
	WordState WordState `json:"word_state"`
	Valid     bool      `json:"valid"` // Valid is true if WordState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWordState) Scan(value interface{}) error {
	if value == nil {
		ns.WordState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WordState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWordState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WordState), nil
}

type Language struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	ApiKeyHash   string             `json:"api_key_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Word struct {
	ID           int64              `json:"id"`
	LanguageID   int64              `json:"language_id"`
	NativeWord   string             `json:"native_word"`
	LearningWord string             `json:"learning_word"`
	Article      pgtype.Text        `json:"article"`
	State        WordState          `json:"state"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
