// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_refresh_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO oauth_refresh_tokens (token_hash, api_key_id, user_id, client_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING token_hash, api_key_id, user_id, client_id, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	TokenHash string             `json:"token_hash"`
	ApiKeyID  int64              `json:"api_key_id"`
	UserID    int64              `json:"user_id"`
	ClientID  string             `json:"client_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (OauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.TokenHash,
		arg.ApiKeyID,
		arg.UserID,
		arg.ClientID,
		arg.ExpiresAt,
	)
	var i OauthRefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.ApiKeyID,
		&i.UserID,
		&i.ClientID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :execrows
DELETE FROM oauth_refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefreshToken, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT token_hash, api_key_id, user_id, client_id, expires_at, created_at FROM oauth_refresh_tokens
WHERE token_hash = $1 AND expires_at > now()
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (OauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i OauthRefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.ApiKeyID,
		&i.UserID,
		&i.ClientID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
