// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_codes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthorizationCode = `-- name: ConsumeAuthorizationCode :one
DELETE FROM oauth_authorization_codes
WHERE code_hash = $1 AND expires_at > now()
RETURNING code_hash, client_id, user_id, redirect_uri, code_challenge, code_challenge_method, expires_at, created_at
`

func (q *Queries) ConsumeAuthorizationCode(ctx context.Context, codeHash string) (OauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, consumeAuthorizationCode, codeHash)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAuthorizationCode = `-- name: CreateAuthorizationCode :one
INSERT INTO oauth_authorization_codes (code_hash, client_id, user_id, redirect_uri, code_challenge, code_challenge_method, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING code_hash, client_id, user_id, redirect_uri, code_challenge, code_challenge_method, expires_at, created_at
`

type CreateAuthorizationCodeParams struct {
	CodeHash            string             `json:"code_hash"`
	ClientID            string             `json:"client_id"`
	UserID              int64              `json:"user_id"`
	RedirectUri         string             `json:"redirect_uri"`
	CodeChallenge       string             `json:"code_challenge"`
	CodeChallengeMethod string             `json:"code_challenge_method"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) (OauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, createAuthorizationCode,
		arg.CodeHash,
		arg.ClientID,
		arg.UserID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
	)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
