// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_clients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO oauth_clients (client_id, client_name, redirect_uris)
VALUES ($1, $2, $3)
RETURNING client_id, client_name, redirect_uris, created_at
`

type CreateOAuthClientParams struct {
	ClientID     string      `json:"client_id"`
	ClientName   pgtype.Text `json:"client_name"`
	RedirectUris []string    `json:"redirect_uris"`
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, createOAuthClient, arg.ClientID, arg.ClientName, arg.RedirectUris)
	var i OauthClient
	err := row.Scan(
		&i.ClientID,
		&i.ClientName,
		&i.RedirectUris,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT client_id, client_name, redirect_uris, created_at FROM oauth_clients
WHERE client_id = $1
`

func (q *Queries) GetOAuthClient(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClient, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ClientID,
		&i.ClientName,
		&i.RedirectUris,
		&i.CreatedAt,
	)
	return i, err
}
