// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CountLanguagesByUser(ctx context.Context, userID int64) (int64, error)
	CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRandomWords(ctx context.Context, arg GetRandomWordsParams) ([]Word, error)
	GetUserByAPIKeyHash(ctx context.Context, apiKeyHash string) (User, error)
	InsertWord(ctx context.Context, arg InsertWordParams) (Word, error)
	ListLanguagesByUser(ctx context.Context, userID int64) ([]Language, error)
	UpdateUserAPIKeyHash(ctx context.Context, arg UpdateUserAPIKeyHashParams) (User, error)
	UpdateWordState(ctx context.Context, arg UpdateWordStateParams) (Word, error)
}

var _ Querier = (*Queries)(nil)
