// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	ConsumeAuthorizationCode(ctx context.Context, codeHash string) (OauthAuthorizationCode, error)
	CountLanguagesByUser(ctx context.Context, userID int64) (int64, error)
	CountWordForms(ctx context.Context, languageID int64) (int64, error)
	CountWords(ctx context.Context, languageID int64) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) (OauthAuthorizationCode, error)
	CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error)
	CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (OauthRefreshToken, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteRefreshToken(ctx context.Context, tokenHash string) (int64, error)
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	DeleteWord(ctx context.Context, arg DeleteWordParams) (int64, error)
	DeleteWordForm(ctx context.Context, arg DeleteWordFormParams) (int64, error)
	GetOAuthClient(ctx context.Context, clientID string) (OauthClient, error)
	GetRandomWordForms(ctx context.Context, arg GetRandomWordFormsParams) ([]GetRandomWordFormsRow, error)
	GetRandomWords(ctx context.Context, arg GetRandomWordsParams) ([]Word, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (OauthRefreshToken, error)
	GetUserByAPIKeyHash(ctx context.Context, keyHash string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetValidSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	InsertWord(ctx context.Context, arg InsertWordParams) (Word, error)
	InsertWordForm(ctx context.Context, arg InsertWordFormParams) (WordForm, error)
	ListAPIKeysByUser(ctx context.Context, userID int64) ([]ApiKey, error)
	ListLanguagesByUser(ctx context.Context, userID int64) ([]Language, error)
	ListWordForms(ctx context.Context, arg ListWordFormsParams) ([]ListWordFormsRow, error)
	ListWords(ctx context.Context, arg ListWordsParams) ([]Word, error)
	SearchWords(ctx context.Context, arg SearchWordsParams) ([]Word, error)
	UpdateWordState(ctx context.Context, arg UpdateWordStateParams) (Word, error)
}

var _ Querier = (*Queries)(nil)
