// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: word_forms.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWordForm = `-- name: DeleteWordForm :execrows
DELETE FROM word_forms
WHERE word_forms.id = $1
  AND word_id IN (
    SELECT w.id FROM words w
    JOIN languages l ON l.id = w.language_id
    WHERE l.user_id = $2
  )
`

type DeleteWordFormParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteWordForm(ctx context.Context, arg DeleteWordFormParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWordForm, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRandomWordForms = `-- name: GetRandomWordForms :many
SELECT
    wf.id,
    wf.word_id,
    wf.subject,
    wf.form,
    wf.tense,
    wf.created_at,
    w.native_word,
    w.learning_word,
    w.state
FROM word_forms wf
JOIN words w ON w.id = wf.word_id
WHERE w.language_id = $1
  AND w.state != 'mastered'
ORDER BY
    (CASE w.state
        WHEN 'new'       THEN 4
        WHEN 'learning'  THEN 3
        WHEN 'confident' THEN 2
        ELSE 1
    END) * random() DESC
LIMIT $2
`

type GetRandomWordFormsParams struct {
	LanguageID int64 `json:"language_id"`
	Limit      int32 `json:"limit"`
}

type GetRandomWordFormsRow struct {
	ID           int64              `json:"id"`
	WordID       int64              `json:"word_id"`
	Subject      string             `json:"subject"`
	Form         string             `json:"form"`
	Tense        pgtype.Text        `json:"tense"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	NativeWord   string             `json:"native_word"`
	LearningWord string             `json:"learning_word"`
	State        WordState          `json:"state"`
}

func (q *Queries) GetRandomWordForms(ctx context.Context, arg GetRandomWordFormsParams) ([]GetRandomWordFormsRow, error) {
	rows, err := q.db.Query(ctx, getRandomWordForms, arg.LanguageID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRandomWordFormsRow
	for rows.Next() {
		var i GetRandomWordFormsRow
		if err := rows.Scan(
			&i.ID,
			&i.WordID,
			&i.Subject,
			&i.Form,
			&i.Tense,
			&i.CreatedAt,
			&i.NativeWord,
			&i.LearningWord,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWordForm = `-- name: InsertWordForm :one
INSERT INTO word_forms (word_id, subject, form, tense)
VALUES ($1, $2, $3, $4)
RETURNING id, word_id, subject, form, created_at, tense
`

type InsertWordFormParams struct {
	WordID  int64       `json:"word_id"`
	Subject string      `json:"subject"`
	Form    string      `json:"form"`
	Tense   pgtype.Text `json:"tense"`
}

func (q *Queries) InsertWordForm(ctx context.Context, arg InsertWordFormParams) (WordForm, error) {
	row := q.db.QueryRow(ctx, insertWordForm,
		arg.WordID,
		arg.Subject,
		arg.Form,
		arg.Tense,
	)
	var i WordForm
	err := row.Scan(
		&i.ID,
		&i.WordID,
		&i.Subject,
		&i.Form,
		&i.CreatedAt,
		&i.Tense,
	)
	return i, err
}
