// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: words.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRandomWords = `-- name: GetRandomWords :many
SELECT id, language_id, native_word, learning_word, article, state, created_at, updated_at FROM words
WHERE language_id = $1
ORDER BY random()
LIMIT $2
`

type GetRandomWordsParams struct {
	LanguageID int64 `json:"language_id"`
	Limit      int32 `json:"limit"`
}

func (q *Queries) GetRandomWords(ctx context.Context, arg GetRandomWordsParams) ([]Word, error) {
	rows, err := q.db.Query(ctx, getRandomWords, arg.LanguageID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Word
	for rows.Next() {
		var i Word
		if err := rows.Scan(
			&i.ID,
			&i.LanguageID,
			&i.NativeWord,
			&i.LearningWord,
			&i.Article,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWord = `-- name: InsertWord :one
INSERT INTO words (language_id, native_word, learning_word, article)
VALUES ($1, $2, $3, $4)
RETURNING id, language_id, native_word, learning_word, article, state, created_at, updated_at
`

type InsertWordParams struct {
	LanguageID   int64       `json:"language_id"`
	NativeWord   string      `json:"native_word"`
	LearningWord string      `json:"learning_word"`
	Article      pgtype.Text `json:"article"`
}

func (q *Queries) InsertWord(ctx context.Context, arg InsertWordParams) (Word, error) {
	row := q.db.QueryRow(ctx, insertWord,
		arg.LanguageID,
		arg.NativeWord,
		arg.LearningWord,
		arg.Article,
	)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.LanguageID,
		&i.NativeWord,
		&i.LearningWord,
		&i.Article,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWordState = `-- name: UpdateWordState :one
UPDATE words
SET state = $2, updated_at = now()
WHERE id = $1
RETURNING id, language_id, native_word, learning_word, article, state, created_at, updated_at
`

type UpdateWordStateParams struct {
	ID    int64     `json:"id"`
	State WordState `json:"state"`
}

func (q *Queries) UpdateWordState(ctx context.Context, arg UpdateWordStateParams) (Word, error) {
	row := q.db.QueryRow(ctx, updateWordState, arg.ID, arg.State)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.LanguageID,
		&i.NativeWord,
		&i.LearningWord,
		&i.Article,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
