// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: words.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWord = `-- name: DeleteWord :execrows
DELETE FROM words
WHERE words.id = $1
  AND language_id IN (SELECT id FROM languages WHERE user_id = $2)
`

type DeleteWordParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteWord(ctx context.Context, arg DeleteWordParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWord, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRandomWords = `-- name: GetRandomWords :many
SELECT id, language_id, native_word, learning_word, article, state, created_at, updated_at FROM words
WHERE language_id = $1
  AND state != 'mastered'
ORDER BY
    (CASE state
        WHEN 'new'       THEN 4
        WHEN 'learning'  THEN 3
        WHEN 'confident' THEN 2
        ELSE 1
    END) * random() DESC
LIMIT $2
`

type GetRandomWordsParams struct {
	LanguageID int64 `json:"language_id"`
	Limit      int32 `json:"limit"`
}

func (q *Queries) GetRandomWords(ctx context.Context, arg GetRandomWordsParams) ([]Word, error) {
	rows, err := q.db.Query(ctx, getRandomWords, arg.LanguageID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Word
	for rows.Next() {
		var i Word
		if err := rows.Scan(
			&i.ID,
			&i.LanguageID,
			&i.NativeWord,
			&i.LearningWord,
			&i.Article,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWord = `-- name: InsertWord :one
INSERT INTO words (language_id, native_word, learning_word, article)
VALUES ($1, $2, $3, $4)
RETURNING id, language_id, native_word, learning_word, article, state, created_at, updated_at
`

type InsertWordParams struct {
	LanguageID   int64       `json:"language_id"`
	NativeWord   string      `json:"native_word"`
	LearningWord string      `json:"learning_word"`
	Article      pgtype.Text `json:"article"`
}

func (q *Queries) InsertWord(ctx context.Context, arg InsertWordParams) (Word, error) {
	row := q.db.QueryRow(ctx, insertWord,
		arg.LanguageID,
		arg.NativeWord,
		arg.LearningWord,
		arg.Article,
	)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.LanguageID,
		&i.NativeWord,
		&i.LearningWord,
		&i.Article,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchWords = `-- name: SearchWords :many
SELECT id, language_id, native_word, learning_word, article, state, created_at, updated_at FROM words
WHERE language_id = $1
  AND learning_word ILIKE '%' || $2::text || '%'
ORDER BY learning_word
LIMIT 20
`

type SearchWordsParams struct {
	LanguageID int64  `json:"language_id"`
	Query      string `json:"query"`
}

func (q *Queries) SearchWords(ctx context.Context, arg SearchWordsParams) ([]Word, error) {
	rows, err := q.db.Query(ctx, searchWords, arg.LanguageID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Word
	for rows.Next() {
		var i Word
		if err := rows.Scan(
			&i.ID,
			&i.LanguageID,
			&i.NativeWord,
			&i.LearningWord,
			&i.Article,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWordState = `-- name: UpdateWordState :one
UPDATE words
SET state = $2, updated_at = now()
WHERE id = $1
RETURNING id, language_id, native_word, learning_word, article, state, created_at, updated_at
`

type UpdateWordStateParams struct {
	ID    int64     `json:"id"`
	State WordState `json:"state"`
}

func (q *Queries) UpdateWordState(ctx context.Context, arg UpdateWordStateParams) (Word, error) {
	row := q.db.QueryRow(ctx, updateWordState, arg.ID, arg.State)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.LanguageID,
		&i.NativeWord,
		&i.LearningWord,
		&i.Article,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
